[package]
name = "elektron"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "elektron"
crate-type = ["rlib", "cdylib"]

[dependencies]
pyo3 = { version = "0.16.5", features = ["extension-module"] }
lazy_static = "1.4.0"
regex = "1.5.6"
clap = { version = "3", features = ["derive"] }
json = "0.12.4"
itertools = "0.10.2"
png = "0.17.5"
svg = "0.10.0"
pdf = "0.7.2"
cairo-rs = { version = "0.15.11", features = ["svg", "png", "pdf"] }
ndarray = "0.15.4"
ngspice-sys = "0.2.1"
libloading = "0.7.3"
thiserror = "1.0.31"
memmap2 = "0.5.4"
plotly = { version = "0.7.0", features = ["kaleido"] }
rand = "0.8.5"
viuer = "0.6.1"
rust-fuzzy-search = "0.1.1"

[build-system]
requires = ["setuptools", "wheel", "setuptools-rust"]

#[package.metadata.maturin]
#python-source = "python"

[features]
default = ["pyo3/extension-module"]

[dependencies.uuid]
version = "1.1.2"
features = [
    "v4",                # Lets you generate random UUIDs
    "fast-rng",          # Use a faster (but still sufficiently random) RNG
    "macro-diagnostics", # Enable better diagnostics for compile-time UUIDs
] 
