name: Publish Python distributions to PyPI and TestPyPI

on:
    push:
      branches: [ master ]
    pull_request:
      branches: [ master ]

jobs:
    build-n-publish:
      name: Build and publish Python distribution
      runs-on: ubuntu-18.04
      steps:
        - uses: actions/checkout@master
        - name: Initialize Python 3.7
        - uses: actions/setup-python@v1
          with:
            python-version: 3.7
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install flake8            
            sudo apt-get install -y -qq libngspice0-dev libpango1.0-dev libcairo2-dev
        - name: Build binary wheel and a source tarball
          run: python setup.py sdist
        - name: Publish distribution to Test PyPI
          uses: pypa/gh-action-pypi-publish@master
          with:
            password: ${{ secrets.test_pypi_password }}
            repository_url: https://test.pypi.org/legacy/
