name: CI

on:
  push:
    branches:
      - main
      - master
    tags:
      - '*'
  pull_request:
  workflow_dispatch:

#permissions:
#  contents: read

jobs:
  linux-wheels:
    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux_2_28_x86_64
    steps:
     - uses: actions/checkout@v1
     - name: Build wheels
       run: |
         curl https://sh.rustup.rs -sSf | sh -s -- -y
         source $HOME/.cargo/env
         rustup default nightly-2019-12-11
         bash .github/workflows/build-wheels.sh
     - uses: actions/upload-artifact@v1
       with:
         name: linux-wheels
         path: wheelhouse/
