name: Build

on: [push, pull_request]

jobs:

  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [x86_64]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: 3.9
        architecture: x64
    - name: Build wheels
      uses: PyO3/maturin-action@v1
      with:
        args: --release --out dist --find-interpreter
        target: ${{ matrix.target }}
        manylinux: manylinux_2_28
        before-script-linux: >
            yum -y install gcc clang openssl-devel openssl-libs libicu libicu-devel graphite2 \
                           graphite2-devel cairo cairo-devel cairo-gobject cairo-gobject-devel \
                           pango pango-devel poppler poppler-devel poppler-glib poppler-glib-devel \
                           gcc bison flex libtool autoconf automake gcc libX11 libX11-devel libXaw \
                           libXaw-devel readline readline-devel &&
            curl -L https://sourceforge.net/projects/ngspice/files/ng-spice-rework/41/ngspice-41.tar.gz/download -o ngspice.tar.gz &&
            tar xfz ngspice.tar.gz && pushd ngspice-41 &&
            mkdir release &&
            cd release &&
            ../configure --with-ngshared --enable-xspice --disable-debug --enable-cider --enable-osdi --enable-openmp &&
            make &&
            make install && popd
    - name: Upload wheels
      uses: actions/upload-artifact@v3
      with:
        name: wheels
        path: dist

